FROM nousresearch/hermes-agent:latest

COPY hermes-config.yaml /opt/hermes/cli-config.yaml.example
COPY docker/hermes-entrypoint.sh /opt/hermes/docker/hermes-entrypoint.sh

RUN chmod +x /opt/hermes/docker/hermes-entrypoint.sh

ENTRYPOINT ["/opt/hermes/docker/hermes-entrypoint.sh"]
